# Impact of NiAl nanolaminate, 4 km/s.

# simulation construction

units      metal
dimension  3
boundary   p p p
atom_style atomic

region       left    block         0.0  257.0    0.0 200 0.0 200
region      right    block             257.0  516  0.0 200 0.0 200



thermo 1

# Read pre-thermalised data, reset timestep
read_restart bilayer-nial09-thermalised.init 
timestep   0.001
reset_timestep 0

# Set potentials
pair_style eam/alloy
pair_coeff * * Mishin-Ni-Al-2009.eam.alloy Ni Al


# Thermodynamic acquire settings
thermo_style custom step time temp press pe ke etotal vol
thermo 100
dump    atomdump all atom 100 run.lammpstrj

compute spatialbins all chunk/atom bin/1d x lower 0.01 ids every compress no units reduced
compute bintemps    all temp/chunk spatialbins temp com yes
compute ke all ke
compute temp all temp

fix     temp_bias          all ave/chunk 1 10 10 spatialbins temp bias bintemps file temp.bias.dat
fix     velocity_x         all ave/chunk 1 10 10 spatialbins vx file vx.dat
fix     velocity_x_highres all ave/chunk 1  1  1 spatialbins vx file hrvx.dat
fix     kinetic_energy     all ave/time 1 1 1 c_ke file ke.dat 
fix     temp               all ave/time 1 1 1 c_temp file temp.dat
# Set microcanonical ensemble
fix     microcanonical     all nve

# Thump dynamics
group          g_left      region left
group         g_right      region right
velocity       g_left      set  20 NULL NULL units box sum yes
velocity      g_right      set -20 NULL NULL units box sum yes
fix      box_contract      all deform 1 x vel -40 remap v units box
run  3798 
unfix box_contract
run 96202 
