#!/bin/bash
#PBS -P y35
#PBS -l walltime=8:00:00
#PBS -l ncpus=96
#PBS -l mem=60GB
#PBS -l jobfs=60GB
#PBS -l wd

module load lammps/29Sep2021
mpirun lmp_openmpi -in ${PBS_JOBNAME}.run > ${PBS_JOBNAME}.out
qsub thermalise6
