#!/bin/bash
#PBS -P y35
#PBS -l walltime=24:00:00
#PBS -l ncpus=32
#PBS -l mem=8GB
#PBS -l jobfs=8GB
#PBS -l wd

module load lammps/29Sep2021
n=8
mpirun -map-by ppr:$((8/$n)):socket:PE=$n lmp_openmpi -sf omp -pk omp $n < ${PBS_JOBNAME}.run > ${PBS_JOBNAME}.out
